version: '2'

services:
  wordpress:
    build: ./docker/wordpress
    depends_on:
      - mysql
    volumes:
      - ./app/themes:/var/www/html/wp-content/themes
    links:
      - mysql
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_PASSWORD: wordpress
  mysql:
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - datastore:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8000:80
    links:
      - mysql
volumes:
  datastore:
